<img src=https://courseware.decoded.com/images/decoded/logo-decoded.png align=left width=100px/>

# Python: Data Processing

---

<small>© COPYRIGHT 2026 DECODED LIMITED. ALL RIGHTS RESERVED. Web: https://decoded.com/ </small>

## Workshop Reference Sheet
We recommend that you bring this resource with you to the workshop as it contains some of the key terms and code used to help you feel more comfortable.

### What to expect

During the workshop, you'll gain familiarity with Python syntax and some of the common data types and data processing tasks including the use of in-built functions, collections and Pythonic loops.

### Key Terms

|   Term | Definition         |
|:-------|:--------------|
| Function scope |  The region inside a function. Variables defined within a function can be accessed here and are not accessible outside of the function scope. |
| Object-oriented programming (OOP) | A programming paradigm that focuses on creating reusable and modular code by organizing data and behavior into objects.|
| Class | A blueprint or a template for creating objects. It defines a set of attributes and methods that describe the object's properties and actions.|
| Object | An instance of a class with its own set of data (attributes) and methods (functions) that operate on that data, as defined by the class.|
| Method | A function that is associated with an object, is defined within a class and is called on an instance of that class.|
| Arguments | The input values or references that are passed to a function or method when it is called.|
| Variadic function | A function that accepts an arbitrary number of arguments that can vary each time the function is called.|
| Global variables | Variables that are defined outside of a function or class, and can be accessed and modified from anywhere in the code. |
| Libraries | Collections of pre-written code modules that contain pre-written functions, methods, and classes providing a set of functionalities and tools to simplify the programming process.|
| Module | A file containing Python definitions and statements for functions, classes, and variables that can be used in other Python programs by importing them.|

---

### Key Python Statements

|   Statement | Definition         | Example      |
|-------:|:--------------|:----------|
|      `sum` | A built-in function that takes an iterable (e.g., list, tuple, set, or string) as an argument and returns the sum of its elements. | `sum([1,2,3])` *# outputs 6* |
|     `def` | A keyword used to define a function, it is followed by the name of the function, a set of parentheses that may include any parameters the function requires, and a colon. The code block that follows the colon is the body of the function, where the code that the function executes is defined. | `def my_function(): ...`|
|     `return` | A statement used to specify the value that a function should return back to the caller of the function. | `def square(x): return x ** 2`|
|`*args`| A syntax that allows a function to accept an arbitrary number of positional arguments. The `*` in `*args` is used to unpack an iterable object, such as a list or tuple, into individual arguments, which can then be used in the function. | `def my_function(*args): ...`|
|`**kwargs`| A syntax that allows a function to accept an arbitrary number of keyword arguments. The `**` in `**kwargs` is used to unpack a dictionary into individual keyword arguments, which can then be used in the function.| `def my_function(**kwargs): ...` |
|      `if` | A conditional statement that is used to execute code only if a certain condition is true. | `if x > 0: print("x is positive")` |
|      `locals` | A built-in function that returns the variables defined in the local scope and their values as a dictionary. | `locals()` |
|      `div` | A built-in function that is used to perform standard division, including division of floating-point numbers. | `div(2, 8)` *# outputs 0.25* |
|      `import` | A keyword that is used to import external modules or libraries in your program. | `import numpy as np` |

<br>

### Challenges

Some of the challenges may not be covered during the workshop and so we recommend you attempt any remaining challenges after the workshop.

<br>

### `Groupby` And `Agg` Exercises

In [14]:
import pandas as pd

attendance = pd.DataFrame(
    {
        "session_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "date": pd.to_datetime([
            "2026-02-01", "2026-02-01", "2026-02-02", "2026-02-02", "2026-02-03",
            "2026-02-03", "2026-02-04", "2026-02-04", "2026-02-05", "2026-02-05"
        ]),
        "programme": ["Data", "Data", "Data", "AI", "AI", "AI", "Data", "AI", "Data", "AI"],
        "location": ["London", "Leeds", "London", "London", "Leeds", "Manchester", "Manchester", "London", "Leeds", "Manchester"],
        "attendees": [12, 18, 15, 10, 14, 9, 20, 11, 16, 13],
        "duration_hours": [2, 3, 2, 1.5, 2, 2.5, 3, 1.5, 2, 2.5],
    }
)
attendance

   session_id       date programme    location  attendees  duration_hours
0           1 2026-02-01      Data      London         12             2.0
1           2 2026-02-01      Data       Leeds         18             3.0
2           3 2026-02-02      Data      London         15             2.0
3           4 2026-02-02        AI      London         10             1.5
4           5 2026-02-03        AI       Leeds         14             2.0
5           6 2026-02-03        AI  Manchester          9             2.5
6           7 2026-02-04      Data  Manchester         20             3.0
7           8 2026-02-04        AI      London         11             1.5
8           9 2026-02-05      Data       Leeds         16             2.0
9          10 2026-02-05        AI  Manchester         13             2.5

#### Exercise 1: How many sessions are there in each location?

In [15]:
attendance.groupby('location')['session_id'].count()

location
Leeds         3
London        4
Manchester    3
Name: session_id, dtype: int64



#### Exercise 2: What is the total number of attendees in each programme?

In [16]:
attendance.groupby('programme')['attendees'].sum()

programme
AI      57
Data    81
Name: attendees, dtype: int64


#### Exercise 3: What is the average number of attendees per session in each location?

In [17]:
attendance.groupby('location')['attendees'].mean()

location
Leeds         16.0
London        12.0
Manchester    14.0
Name: attendees, dtype: float64


#### Exercise 4: What is the minimum session duration for each programme?

In [18]:
attendance.groupby('programme')['duration_hours'].min()

programme
AI      1.5
Data    2.0
Name: duration_hours, dtype: float64


#### Exercise 5: What is the maximum session duration for each programme?

In [19]:
attendance.groupby('programme')['duration_hours'].max()

programme
AI      2.5
Data    3.0
Name: duration_hours, dtype: float64


#### Exercise 6: What is the median number of attendees per programme?

In [20]:
attendance.groupby('programme')['attendees'].median()

programme
AI      11.0
Data    16.0
Name: attendees, dtype: float64


#### Exercise 7: How many sessions took place on each date?

In [21]:
attendance.groupby('location')['session_id'].count()

location
Leeds         3
London        4
Manchester    3
Name: session_id, dtype: int64


### For the proceeding exercise us `.agg()`

#### Exercise 8: For each location, how many sessions are there and what is the total number of attendees?

In [24]:
# .agg() multiple metrics
attendance.groupby('location').agg(
    session_no=('session_id', 'count'),
    median=('attendees', 'sum')
).reset_index()

     location  session_no  median
0       Leeds           3      48
1      London           4      48
2  Manchester           3      42

#### Exercise 9: For each programme, what is the average and median session size?

In [26]:
attendance.groupby('programme').agg(
    avg_session=('attendees', 'mean'),
    median_session=('attendees', 'median')
).reset_index()

  programme  avg_session  median_session
0        AI         11.4            11.0
1      Data         16.2            16.0

#### Exercise 10: For each location, what is the minimum and maximum session duration?

In [28]:
attendance.groupby('location').agg(
    min_duration=('duration_hours', 'min'),
    max_duration=('duration_hours', 'max')
).reset_index()

     location  min_duration  max_duration
0       Leeds           2.0           3.0
1      London           1.5           2.0
2  Manchester           2.5           3.0

### Exercises on functions

#### Exercise 1
Write a function that takes a number,
adds 5 to it, then multiplies the result by 2,
and returns the final result.

#### Exercise 2
Write a function that takes a word,
converts it to uppercase,
adds an exclamation mark at the end,
and returns the final string.

### Exercise 3
Write a function that takes a name and a year of birth,
calculates the age assuming the current year is 2026,
and returns a sentence like: "Alex is 26 years old".

### Exercise 4
Write a function that calculates the total price after tax.
It should take a price and an optional tax_rate.
If no tax_rate is provided, assume 20% (0.2).
Return the final price.

### Exercise 5:
Write a function that takes a number.
First, calculate the square of the number.
then, return a string that says:
"The result is (number)"

## Pandas Conditional Filtering Exercises

In [2]:
import pandas as pd
df = pd.DataFrame({

    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],

    "region": [

        "London", "London", "Manchester", "London",

        "Birmingham", "Manchester", "London", "Birmingham"

    ],

    "category": [

        "Food", "Tech", "Food", "Food",

        "Tech", "Food", "Tech", None

    ],

    "sales": [1200, 800, 400, 1500, 2000, 300, 500, 900],

    "cost":  [700, 900, 300, 600, 1200, 350, 600, 400]

})

df

   order_id      region category  sales  cost
0       101      London     Food   1200   700
1       102      London     Tech    800   900
2       103  Manchester     Food    400   300
3       104      London     Food   1500   600
4       105  Birmingham     Tech   2000  1200
5       106  Manchester     Food    300   350
6       107      London     Tech    500   600
7       108  Birmingham      NaN    900   400

### Exercise 1 — Single condition (numeric)
- Select all orders where sales are greater than 1,000

In [3]:
df[df['sales'] > 1000]

   order_id      region category  sales  cost
0       101      London     Food   1200   700
3       104      London     Food   1500   600
4       105  Birmingham     Tech   2000  1200

### Exercise 2 — Single condition (categorical)
- Select all orders where the region is Birmingham

In [4]:
df[df['region'] == 'Birmingham']

   order_id      region category  sales  cost
4       105  Birmingham     Tech   2000  1200
7       108  Birmingham      NaN    900   400

### Exercise 3 — Multiple conditions (AND)
#### Select all orders where:
- category is "Food"
- cost is less than 500

In [5]:
df[(df['category'] == 'Food') & (df['cost'] < 500)]

   order_id      region category  sales  cost
2       103  Manchester     Food    400   300
5       106  Manchester     Food    300   350

### Exercise 4 — Multiple values (membership)
#### Select all orders where the region is either Manchester or Birmingham

In [6]:
df[df['region'].isin(['Manchester', 'Birmingham'])]

   order_id      region category  sales  cost
2       103  Manchester     Food    400   300
4       105  Birmingham     Tech   2000  1200
5       106  Manchester     Food    300   350
7       108  Birmingham      NaN    900   400

### Exercise 5 — Missing values OR text matching
#### Select all orders where:
- category is missing OR
- category contains the word "food" (case‑insensitive)

In [8]:
df[(df['category'].isna()) | (df['category'].str.contains('food', case=False))]

   order_id      region category  sales  cost
0       101      London     Food   1200   700
2       103  Manchester     Food    400   300
3       104      London     Food   1500   600
5       106  Manchester     Food    300   350
7       108  Birmingham      NaN    900   400

In [12]:
# 
df.filter(like='0', axis=0)

   order_id  region category  sales  cost
0       101  London     Food   1200   700

---