<img src=https://courseware.decoded.com/images/decoded/logo-decoded.png align=left width=100px/>

# Python: Further Data Manipulation

---

<small>© COPYRIGHT 2026 DECODED LIMITED. ALL RIGHTS RESERVED. Web: https://decoded.com/ </small>

## Learning Objectives

1. **Series** Understanding Series as the building blocks of Dataframes and their behaviour
2. **Loc vs Iloc:** Understanding the problems that occur from inconsistent indexing and how .iloc and loc fix it
3. **Conditional Filtering:** Learning how to apply a variety of filter conditions to extract specific columns and rows based a on a condition
4. **Aggregating Data** Learn how to quickly wrangle data with aggregates
5. **Introduction To Functions** Discover how functions are used in the context of Data Science and learn some write some yourself


---



### Programmes

* Workshop 1.2 - Data Science Accelerator

###Workshop Summary

This chapter will expand upon the first session introducing key techniques used in data manipulation from indexing to aggregation and introducing the idea of data preprocessing



*   What is advanced data manipulation in Python?
    *   What does “data manipulation” mean beyond basic cleaning?
    *   How does pandas build on Python fundamentals?
    *   When should I think in rows, columns, or vectors?
*   Working with `pandas.Series`
    *   What is a `Series` and how does it differ from a list?
    *   How do indexing and slicing work in a `Series`?
    *   How can a `Series` behave like:
        *   a dictionary (key–value access)
        *   a NumPy array (vectorised operations)
*   Label-based vs position-based indexing
    *   What problem do `.loc` and `.iloc` solve?
    *   How do labels differ from integer positions?
    *   How do you safely subset data using:
        *   row labels
        *   column labels
        *   row/column positions
*   Conditional filtering in pandas
    *   How do you filter data using boolean conditions?
    *   How do comparison operators work on entire columns?
    *   How do you combine multiple conditions correctly?
    *   Why is conditional filtering foundational for analysis?
*   Aggregating data with pandas
    *   What does aggregation mean in data analysis?
    *   How do you summarise data using:
        *   `sum`, `mean`, `count`, `min`, `max`
    *   How does aggregation change the “shape” of data?
    *   When do you aggregate before vs after filtering?
*   Performant data manipulation with NumPy
    *   Why performance matters for large datasets
    *   What is vectorisation and why is it faster than loops?
    *   How NumPy executes operations at scale
    *   Comparing:
        *   Python loops
        *   NumPy vectorised operations
*   Functions for data preprocessing
    *   Why repeated preprocessing logic is a problem
    *   How functions improve:
        *   reusability
        *   readability
        *   consistency
    *   Encapsulating data-cleaning logic into functions
*   Limitations of ad-hoc preprocessing
    *   Why “one-off” cleaning code does not scale
    *   Common problems with:
        *   copy-paste logic
        *   hidden assumptions
        *   fragile pipelines
    *   The need for structured, repeatable preprocessing
*   Review
    *   What did we learn?
    *   How pandas and NumPy fit together in practice
    *   How this prepares you for feature engineering and machine learning
*   What should I learn next?
    *   GroupBy operations and split-apply-combine
    *   Feature engineering patterns
    *   Data validation and schema enforcement
    *   Preprocessing with scikit-learn pipelines

### Applications: Why study Data Processing in Python?

This section set up the foundational knowledge needed to work directly with data in python and introduces concepts and practices that support the ingestion phase of a ML pipelline

## Data Manipulation - `Series` Slicing & Index

---

## Series as a dictionary

below we can see that the a series behaves similary to a standard dictionary

In [1]:
import pandas as pd
data = pd.Series([10,22,33,44],name="attendance")

In [2]:
#display the Series
data

0    10
1    22
2    33
3    44
Name: attendance, dtype: int64

In [4]:
# access element by label (
data[1]

np.int64(22)

In [7]:
# membership test in Series
3 in data

True

In [9]:
# list keys of Series
list(data.keys())

[0, 1, 2, 3]

In [11]:
#list series items
list(data.items())

[(0, 10), (1, 22), (2, 33), (3, 44)]

### Series as a Numpy array

Here we will show that a series can be indexed in a way similar to numpy array as seen in the previous session

In [12]:
# add a value to across all element
data + 5

0    15
1    27
2    38
3    49
Name: attendance, dtype: int64

In [13]:
#times a value across all element
data * 2

0    20
1    44
2    66
3    88
Name: attendance, dtype: int64

In [16]:
# add a list of numbers
data + [1,2,3,4]

0    11
1    24
2    36
3    48
Name: attendance, dtype: int64

---

# Data Manipulation - .loc and .iloc

---

In [17]:
import pandas as pd

sales = pd.DataFrame({
    "revenue": [1200, 1500, 1100, 1800,200]
}, index=pd.to_datetime([
    "2024-01-01",
    "2024-01-02",
    "2024-01-03",
    "2024-01-04",
    "2024-01-04"
]))

sales

            revenue
2024-01-01     1200
2024-01-02     1500
2024-01-03     1100
2024-01-04     1800
2024-01-04      200

Example

In [20]:
#using integer based indexing - iloc
sales.iloc[0]

revenue    1200
Name: 2024-01-01 00:00:00, dtype: int64

In [21]:
#using label based indexing - loc
sales.loc["2024-01-01"]

revenue    1200
Name: 2024-01-01 00:00:00, dtype: int64

In [22]:
sales.loc["2024-01-04"]

            revenue
2024-01-04     1800
2024-01-04      200

---

# Data Manipulation - Conditional Filtering

---

### Select all rows where region is London

In [23]:
df = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "region": [
        "London", "London", "Manchester", "London",
        "Birmingham", "Manchester", "London", "Birmingham"
    ],
    "category": [
        "Food", "Tech", "Food", "Food",
        "Tech", "Food", "Tech", None
    ],
    "sales": [1200, 800, 400, 1500, 2000, 300, 500, 900],
    "cost":  [700, 900, 300, 600, 1200, 350, 600, 400],
})

### Action: filter rows where region == 'London'

In [24]:
df[df['region'] == 'London']

   order_id  region category  sales  cost
0       101  London     Food   1200   700
1       102  London     Tech    800   900
3       104  London     Food   1500   600
6       107  London     Tech    500   600

### Select all rows where cost is greater than 500

In [25]:
df[df['cost'] > 500]

   order_id      region category  sales  cost
0       101      London     Food   1200   700
1       102      London     Tech    800   900
3       104      London     Food   1500   600
4       105  Birmingham     Tech   2000  1200
6       107      London     Tech    500   600

### Select all rows where cost is greater than 600 and region is London

In [26]:
df[(df['cost'] > 600) & (df['region'] == 'London')]

   order_id  region category  sales  cost
0       101  London     Food   1200   700
1       102  London     Tech    800   900

### Select all rows where region is either London, Manchester or France

In [27]:
df[df['region'].isin(['London', 'Manchester', 'France'])]

   order_id      region category  sales  cost
0       101      London     Food   1200   700
1       102      London     Tech    800   900
2       103  Manchester     Food    400   300
3       104      London     Food   1500   600
5       106  Manchester     Food    300   350
6       107      London     Tech    500   600

### Select all rows where category is missing

In [28]:
df[df['category'].isna()]

   order_id      region category  sales  cost
7       108  Birmingham      NaN    900   400

### Select all rows where category contains 'ec' (case insensitive)

In [34]:
df[df['category'].str.contains('ec', case=False)]

   order_id      region category  sales  cost
1       102      London     Tech    800   900
4       105  Birmingham     Tech   2000  1200
6       107      London     Tech    500   600

What does it look like we

Doing stuff with the filtered rows

In [12]:
#e.g find the count of sales per city
london_orders = df[df["region"] == "London"]["sales"].count()
manchester_count = df[df["region"]=="Manchester"]["sales"].count()
birmingham_count = df[df["region"]=="Birmingham"]["sales"].count()

# Aggregating Data With Pandas

---

In [35]:
# Data question: What does our raw transactional dataset look like before any summarisation?
import pandas as pd

df = pd.DataFrame(
    {
        "order_id":  [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010],
        "date":      pd.to_datetime(["2026-01-02","2026-01-02","2026-01-03","2026-01-03","2026-01-04",
                                     "2026-01-04","2026-01-05","2026-01-05","2026-01-06","2026-01-06"]),
        "customer":  ["C001","C002","C001","C003","C004","C002","C005","C001","C003","C006"],
        "city":      ["London","London","London","Manchester","Manchester","London","Birmingham","London","Manchester","Birmingham"],
        "category":  ["Coffee","Coffee","Tea","Coffee","Tea","Tea","Coffee","Coffee","Tea","Coffee"],
        "qty":       [2,1,3,1,2,1,4,1,2,1],
        "unit_price":[3.50,3.50,2.40,3.50,2.40,2.40,3.50,3.50,2.40,3.50],
    }
)

df["revenue"] = df["qty"] * df["unit_price"]
df

   order_id       date customer        city category  qty  unit_price  revenue
0      1001 2026-01-02     C001      London   Coffee    2         3.5      7.0
1      1002 2026-01-02     C002      London   Coffee    1         3.5      3.5
2      1003 2026-01-03     C001      London      Tea    3         2.4      7.2
3      1004 2026-01-03     C003  Manchester   Coffee    1         3.5      3.5
4      1005 2026-01-04     C004  Manchester      Tea    2         2.4      4.8
5      1006 2026-01-04     C002      London      Tea    1         2.4      2.4
6      1007 2026-01-05     C005  Birmingham   Coffee    4         3.5     14.0
7      1008 2026-01-05     C001      London   Coffee    1         3.5      3.5
8      1009 2026-01-06     C003  Manchester      Tea    2         2.4      4.8
9      1010 2026-01-06     C006  Birmingham   Coffee    1         3.5      3.5

### How many orders do we have in each city?

In [37]:
df.groupby('city')['order_id'].count()

city
Birmingham    2
London        5
Manchester    3
Name: order_id, dtype: int64

### What is the total revenue generated in each city?

In [38]:
df.groupby('city')['revenue'].sum()

city
Birmingham    17.5
London        23.6
Manchester    13.1
Name: revenue, dtype: float64

### What is the average order revenue in each city?

In [40]:
df.groupby('city')['revenue'].mean()

city
Birmingham    8.750000
London        4.720000
Manchester    4.366667
Name: revenue, dtype: float64

### What is the smallest (minimum) order revenue we see in each city?

In [41]:
df.groupby('city')['revenue'].min()

city
Birmingham    3.5
London        2.4
Manchester    3.5
Name: revenue, dtype: float64

### What is the largest (maximum) order revenue we see in each city?

In [42]:
df.groupby('city')['revenue'].max()

city
Birmingham    14.0
London         7.2
Manchester     4.8
Name: revenue, dtype: float64

### What is the typical order revenue in each city (less sensitive to outliers than the mean)?

In [47]:
df.groupby('city')['revenue'].median()

city
Birmingham    8.75
London        3.50
Manchester    4.80
Name: revenue, dtype: float64

### How consistent are order revenues in each city (i.e., how much do they vary)?

In [48]:
df.groupby('city')['revenue'].std()

city
Birmingham    7.424621
London        2.219685
Manchester    0.750555
Name: revenue, dtype: float64

# Introducing `.agg()` — combining multiple aggregates

### What does `.agg()` do?

The `.agg()` method allows us to:

- Apply **multiple aggregate functions at once**
- Give **clear names** to each aggregated output
- Produce **one tidy summary table** instead of many separate ones

In [62]:
# .agg()
df.groupby('city').agg(order=('order_id', 'count'),total_revenue=('revenue', 'sum'))

            order  total_revenue
city
Birmingham      2           17.5
London          5           23.6
Manchester      3           13.1

In [64]:
# .agg() multiple metrics
df.groupby('city').agg(
    avg_order=('revenue', 'mean'),
    median=('revenue', 'median')
).reset_index()

         city  avg_order  median
0  Birmingham   8.750000    8.75
1      London   4.720000    3.50
2  Manchester   4.366667    4.80

In [ ]:
#.agg() unique customers & max

---

## Performant Data Manipulation With Numpy

In standard Python, we use `for` loops. In Data Science, looping over 10 million rows is too slow. Here we introduce numpy and show the improvements from  **Vectorization**."

---

### Vectorised Math vs. Loops
**Scenario:** Calculate the Natural Log `ln()` of revenue.

##### Generate big data for the test (1 Million Rows)

In [65]:
import numpy as np
import pandas as pd
import time
import math

# Generate big data for the test (10 Million Rows)
big_data = np.random.rand(10_000_000) * 1000
df_big = pd.DataFrame({'revenue': big_data})
df_big.head(5)

      revenue
0  456.037535
1  924.570911
2  607.261746
3  785.058986
4  889.529291

In [67]:
# show shape of big_data
df_big.shape

(10000000, 1)

In [73]:
# loop timing
start = time.time()
res=[]
for num in df_big['revenue']:
    res.append(math.log(num))
end = time.time()
print(f"Time taken s: {end-start: .4f}")

Time taken s:  1.2200

In [ ]:
#numpy vectorization timing

In [ ]:
#generate two arrays and time addition

In [ ]:
#  fromiter looping example

---

# FUNCTIONS FOR DATA PREPROCESSING

---

## Why do we need functions?

Before introducing functions, it’s important to understand **the problem they are solving**.

In real data work — especially during **data preprocessing** — you will often:

- Clean **multiple columns in the same way**
- Copy and paste **working code** to move faster
- Make **small tweaks** as requirements evolve

At first, this approach feels efficient.

---

### The hidden problem

As your dataset grows and your logic changes, this pattern quietly introduces risks:

- Repeated logic becomes **hard to update**
- Small changes can lead to **inconsistent behaviour**
- Bugs are more likely to appear in **only some places**

---

### Why this example is written this way

This example is written for you as a **data analyst transitioning toward data science**.

It deliberately **starts by repeating code**, so you can:

- Clearly see the **pain points**
- Feel why the approach stops scaling
- Understand **why functions exist**, before learning how to write them

### An simulated example

In [ ]:
import pandas as pd
import numpy as np

# Simulated raw data
df = pd.DataFrame({
    "city_a": [" London ", "PARIS", None, "  berlin"],
    "city_b": [" madrid", None, "ROME ", " Lisbon"],
    "city_c": [None, " ATHENS", "vienna ", "  Prague"]
})

df

In [ ]:
# Clean city_a
df["city_a"] = (
    df["city_a"]
    .fillna("unknown")
    .str.strip()
    .str.lower()
)

# Clean city_b
df["city_b"] = (
    df["city_b"]
    .fillna("unknown")
    .str.strip()
    .str.lower()
)

# Clean city_c
df["city_c"] = (
    df["city_c"]
    .fillna("unknown")
    .str.strip()
    .str.lower()
)

df

#### We can create a custom function to help us streamline the workflow

In [ ]:
def clean_text_column(series: pd.Series) -> pd.Series:
    return (
        series
        .fillna("unknown")
        .str.strip()
        .str.lower()
    )

#### Mixing with pythonic loops to make script cleaner

In [ ]:
for col in ["city_a", "city_b", "city_c"]:
    df[col] = clean_text_column(df[col])

df

# Why does this matter?

- Single source of truth for preprocessing logic

- Easier experimentation (change once, apply everywhere)

- Functions compose cleanly into pipelines later (e.g. sklearn)

- Clear boundary between what you do and where you do it

- This is the first step toward reproducible, testable preprocessing pipelines.

## Function Syntax

In [ ]:
def function_name(parameter1, parameter2):
    """Optional description of what the function does."""
    # function body (indented)
    result = parameter1 + parameter2
    return result

## Python Function Anatomy

**def**  
- Short for *define*  
- Tells Python you are creating a function  

**function_name**  
- How you refer to and call the function later  
- Should describe what the function does  

**(parameter1, parameter2)**  
- Parameters are inputs to the function  
- Both inputs must be provided when calling the function  

**:**  
- Marks the start of the function body  

**Indentation**  
- Everything indented underneath belongs to the function  
- This is how Python knows what code is inside the function  

**return**  
- Sends a value back to where the function was called  
- Ends the function immediately

## Function Examples

### 1. A function can take one input and returns one output

In [ ]:

def double(number):
    return number * 2

double(4)

### 2. The same function can be reused with different values

In [ ]:

def add_exclamation(text):
    return text + "!"

add_exclamation("hello")
add_exclamation("great")
add_exclamation("wow")

### 3. A function can accept more than one input

In [ ]:

def full_name(first, last):
    return first + " " + last

full_name("Ada", "Lovelace")

### 4. I can set parameters to have default values

In [ ]:
def greet(name, greeting="Hello"):
    return greeting + ", " + name

greet("Sam")
greet("Sam", greeting="Hi")

#### 5. Interestingly, without `return`, the function returns `None`

In [ ]:
def announce(message):
    print(message)

result=announce("Starting program")
print(result)